### ISSUE TITLE
FATAL ERROR: CANNOT USE OBJECT OF TYPE STDCLASS AS ARRAY...

### ISSUE THREAD

**Issue by ghost** [lewismcarey/User-Field-ACF-Add-on#14]
I keep getting the following error:

FATAL ERROR: CANNOT USE OBJECT OF TYPE STDCLASS AS ARRAY IN

I added this to my functions.php file

` function get_author() {
    $postid = get_the_ID();
    $authors = get_field('author', $postid);

```
if($authors) {    
    foreach($authors as $author) {
        echo 'By '. $author['user_email'] .' on ';      
    }     
}
```

}`

and this in my page template: 

`echo get_author();`

Any suggestions?

**Comment by trewknowledge** [comment]
Needed to use $author->user_email
