### ISSUE TITLE
Can't seem to get this working.

### ISSUE THREAD

**Issue by ghost** [lewismcarey/User-Field-ACF-Add-on#15]
I am having a bit of an issue trying to get this to work on my site. 

I added the following code

'$author = get_field('author'); 
if ($author) {
  echo 'By '. $author["display_name"] .' on ';
}'

But I get the following error:
Fatal error: Cannot use object of type WP_User as array

Anything I am doing wrong?

**Comment by trewknowledge** [comment]
Solved it. Had to use  $author->display_name;
