### ISSUE TITLE
$values and $value->user_description

### ISSUE THREAD

**Issue by tobyskyring** [lewismcarey/User-Field-ACF-Add-on#17]
When i print out $values i get data for everything except user_description?

In addition to this would be really nice if we could grab the user gravatar if possible?

**Comment by tobyskyring** [comment]
Here's a screenshot
![Screen Shot 2013-01-11 at 3 50 12 PM](https://f.cloud.github.com/assets/409344/59213/7b37e35c-5baa-11e2-9f75-3e9529ce296b.png)

**Comment by shaunbent** [comment]
Wordpress changed what data was returned via get_userdata() as such it broke the data this add-on was returning. This has none been address.
