### ISSUE TITLE
PHP error on line 407

### ISSUE THREAD

**Issue by jacobdubail** [lewismcarey/User-Field-ACF-Add-on#20]
Thanks for creating this extension.  It's saving me tons of time.

Here's my code (it's within the author.php template).

<?php
$prev = get_field('prev_user', 'user_'.$curauth->ID );
$next = get_field('_user', 'user_'.$curauth->ID );

  if ( !empty($prev) ) :
    print_r($prev);
  endif; 
  if ( !empty($next) ) :
    print_r($next);
  endif;
?>

This results in the following error:

Warning: Invalid argument supplied for foreach() in .../acf_users_field.php on line 407

I have a single user selected for each of the fields, but get this error no matter what I do.  Any ideas?

Thanks,
Jacob

**Comment by shaunbent** [comment]
I've been unable to recreate this issue, I can only assume that different versions of PHP are a little bit more lenient with what you can pass into a foreach.

I have basically forced $values to be an array regardless of its a single users or not.

Could you let me know if thats sorted it.

**Comment by shaunbent** [comment]
Someone else has reported that the above fix does resolve this issue.

**Comment by pflans** [comment]
I had the same problem with single users. This fix 

> $value = (array) $value;

Did not work for me, it erased the data being returned. What ended up fixing it for me (not sure if it retains the original functionality though) is wrapping the entire foreach statement in:

> if (is_array($value)){
