### ISSUE TITLE
Custom roles

### ISSUE THREAD

**Issue by naillizard** [lewismcarey/User-Field-ACF-Add-on#5]
Hi,

Might have to add a role separator field? or use $wp_roles->role_objects.

i.e. If you have a custom role labeled Contract Manager and named contract_manager or even contractmanager, get_editable_roles() always return the label instead of role-name, this will cause get_users(array('role' => 'Contract Manager')) to not return the users for the role, as get_users actually fetches based on the role-name, not label.

**Comment by naillizard** [comment]
Sorry, clicked on the wrong button...

**Comment by naillizard** [comment]
Forked and fixed this issue, would be good if you could merge the changes if you approve it.
https://github.com/diegotdai/User-Field-ACF-Add-on/commit/dede797ac46121c1950827ddfe8334c5c85669e8

**Comment by lewismcarey** [comment]
Hello diegotdai

I have been away, sorry for the delay.
I would be happy to merge - do you need to issue a pull request?

Lewis

**Comment by naillizard** [comment]
Done, sorry forgot to do that.

**Comment by lewismcarey** [comment]
Committed. Thanks for your work and help.
